
# SwiftLint configuration aligned with Apple's Open Source Swift Style
# https://github.com/apple/swift/blob/main/CONTRIBUTING.md#code-style

disabled_rules:
  - trailing_newline
  - legacy_objc_type
  - file_length
  - function_body_length
  - type_body_length
  - identifier_name # Apple often uses short loop vars like i, j, etc.

opt_in_rules:
  - attributes
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_header
  - force_unwrapping
  - joined_default_parameter
  - missing_docs
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_imports
  - switch_case_alignment
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

line_length: 120

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - x
    - y
    - i
    - j

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  ignores_case_statements: true
