# See https://pre-commit.com/ for more information
# See https://pre-commit.com/hooks.html for more hooks
# This file is managed by the pre-commit-configs installer.
# Default configurations (optional)
default_stages: [pre-commit] # Sensible default
default_install_hook_types: [pre-commit, pre-push, commit-msg]
# default_language_version:
#   python: python3.9
repos:
  # Add hooks here using the installer or manually
# --- BEGIN MANAGED TEMPLATES ---
# SwiftLint Hook
- repo: https://github.com/realm/SwiftLint
  rev: 0.58.0
  hooks:
  - id: swiftlint
    name: swiftlint
    description: "Lint Swift files"
    args: [--autocorrect, --config, .swiftlint.yml]
    types: [swift]
    require_serial: true
# SwiftFormat Hook
- repo: https://github.com/nicklockwood/SwiftFormat
  rev: 0.52.9
  hooks:
  - id: swiftformat
    name: swiftformat
    description: "Auto-format Swift files"
    args: [
      --swiftversion, "5.9",
      --config, .swiftformat,
      --quiet,
      --header, strip,
      --trimwhitespace, always,
      --stripunusedargs, closure-only,
      --self, remove
    ]
    types: [swift]
    require_serial: true
# --- END MANAGED TEMPLATES ---
